<template>
  <div>
    <songs class="itemstyle" v-for="(item,i) of songslist" :key="i" :id="item.id" :title="item.title" :subtitle="item.subtitle" :imgurl="require('../../assets/'+songslist[i].pic)" :itemClick="clickitem"></songs>
  </div>
</template>
<script>
import Songs from "./Songs"
export default {
  data(){
    return{
      songslist:[
        {
          pic:"CsYa.jpg",
          iconName:"",
          playCount:"1.3亿"
        },
        {
          pic:"CsYa.jpg",
          iconName:"",
          playCount:"99万"
        },
        {
          pic:"CsYa.jpg",
          iconName:"",
          playCount:"16.7万"
        },
        {
          pic:"CsYa.jpg",
          iconName:"",
          playCount:"23.9万"
        },
        {
          pic:"CsYa.jpg",
          iconName:"",
          playCount:"88万"
        },
        {
          pic:"CsYa.jpg",
          iconName:"",
          playCount:"54万"
        },{
          pic:"CsYa.jpg",
          iconName:"",
          playCount:"99万"
        },
        {
          pic:"CsYa.jpg",
          iconName:"",
          playCount:"16.7万"
        }
      ]
    }
  },
  created(){
    console.log(123);
  },
  methods:{
    clickitem(id){
      console.log(id);
    }
  },
  components:{
    "songs":Songs
  }
}
</script>
<style scoped>
  .itemstyle{
    display: flex;
  }
</style>